#!/bin/bash

#PBS -N timeseries
#PBS -q regular
#PBS -l select=1:ncpus=48:mpiprocs=48
#PBS -l walltime=2:00:00

today="$(date '+%Y%m%d-%H%M%S')"
log_filename=/home/geostrat/cases/CASENAME/postprocess/logs/timeseries.log.$today


mpirun -n 48 apptainer run -B /home,/scratch /opt/ncar/containers/postprocessing /opt/ncar/cesm_postprocessing/cesm-env2/bin/cesm_tseries_generator.py  --caseroot /home/geostrat/cases/CASENAME/postprocess >> ${log_filename}

rm -f /home/geostrat/cases/CASENAME/postprocess/logs/ts_status.log

